// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

using System.Text;
using SharpEmu.Libs.Agc;

namespace SharpEmu.ShaderCompiler.Metal;

/// <summary>
/// Gen5 (gfx10) -> Metal Shading Language compute codegen. Experimental spike proving
/// that the SPIR-V translator's input contract — (Gen5ShaderState, Gen5ShaderEvaluation)
/// out of Gen5ShaderTranslator — is a viable pivot for per-backend shader emitters.
///
/// Register model: every SGPR/VGPR is a typeless 32-bit <c>uint</c> local, matching the
/// hardware register file; float ALU ops bitcast through <c>as_type&lt;float&gt;</c>. EXEC is
/// s126 (exec_lo), initialized all-lanes-on; VALU writes and buffer stores are guarded by
/// the current lane's EXEC bit, mirroring the SPIR-V translator's per-lane exec guard.
/// Guest buffers surface as <c>device uint*</c> arguments bound in the order of
/// <see cref="Gen5ShaderEvaluation.GlobalMemoryBindings"/>.
///
/// Coverage is deliberately the straight-line subset the test fixtures exercise;
/// everything else fails loudly with the offending opcode so gaps stay visible.
/// </summary>
internal static class Gen5MslTranslator
{
    private const uint ExecLoRegister = 126;

    public static bool TryCompileComputeShader(
        Gen5ShaderState state,
        Gen5ShaderEvaluation evaluation,
        uint threadgroupSizeX,
        uint threadgroupSizeY,
        uint threadgroupSizeZ,
        out Gen5MslShader? shader,
        out string error)
    {
        shader = null;
        error = string.Empty;

        var bindingIndexByPc = new Dictionary<uint, int>();
        for (var index = 0; index < evaluation.GlobalMemoryBindings.Count; index++)
        {
            foreach (var pc in evaluation.GlobalMemoryBindings[index].InstructionPcs)
            {
                bindingIndexByPc[pc] = index;
            }
        }

        if (!TryCollectRegisters(state, out var scalarRegisters, out var vectorRegisters, out error))
        {
            return false;
        }

        var body = new StringBuilder();
        foreach (var instruction in state.Program.Instructions)
        {
            if (!TryEmitInstruction(instruction, bindingIndexByPc, body, out error))
            {
                error = $"pc=0x{instruction.Pc:X4} {instruction.Opcode}: {error}";
                return false;
            }
        }

        var source = new StringBuilder();
        source.AppendLine("// Generated by SharpEmu Gen5MslTranslator (experimental spike).");
        source.AppendLine("#include <metal_stdlib>");
        source.AppendLine();
        source.AppendLine("using namespace metal;");
        source.AppendLine();
        source.AppendLine("kernel void gen5_cs(");
        for (var index = 0; index < evaluation.GlobalMemoryBindings.Count; index++)
        {
            source.AppendLine($"    device uint* guest_buffer{index} [[buffer({index})]],");
        }

        source.AppendLine("    uint gen5_lane [[thread_index_in_simdgroup]])");
        source.AppendLine("{");
        source.AppendLine("    const uint gen5_lane_mask = 1u << gen5_lane;");

        foreach (var register in scalarRegisters.Order())
        {
            var initial = register == ExecLoRegister
                ? 0xFFFFFFFFu
                : register < evaluation.InitialScalarRegisters.Count
                    ? evaluation.InitialScalarRegisters[(int)register]
                    : 0u;
            var note = register == ExecLoRegister ? " // exec_lo, all lanes on" : string.Empty;
            source.AppendLine($"    uint s{register} = 0x{initial:X8}u;{note}");
        }

        foreach (var register in vectorRegisters.Order())
        {
            source.AppendLine($"    uint v{register} = 0u;");
        }

        source.AppendLine();
        source.Append(body);
        source.AppendLine("}");

        shader = new Gen5MslShader(
            source.ToString(),
            "gen5_cs",
            evaluation.GlobalMemoryBindings,
            threadgroupSizeX,
            threadgroupSizeY,
            threadgroupSizeZ);
        return true;
    }

    private static bool TryEmitInstruction(
        Gen5ShaderInstruction instruction,
        IReadOnlyDictionary<uint, int> bindingIndexByPc,
        StringBuilder body,
        out string error)
    {
        error = string.Empty;
        body.AppendLine($"    // pc=0x{instruction.Pc:X4} {Describe(instruction)}");

        switch (instruction.Opcode)
        {
            case "SEndpgm":
                body.AppendLine("    return;");
                return true;

            // Scheduling/wait hints carry no data semantics for a single emitted kernel.
            case "SClause":
            case "SWaitcnt":
            case "SWaitcntDepctr":
            case "SNop":
                body.AppendLine("    // scheduling hint, no code");
                return true;

            case "SMovB32":
                if (!TryGetRawSource(instruction, 0, out var scalarValue, out error) ||
                    !TryGetScalarDestination(instruction, out var scalarDestination, out error))
                {
                    return false;
                }

                // Scalar ALU is not EXEC-gated on the hardware.
                body.AppendLine($"    s{scalarDestination} = {scalarValue};");
                return true;

            case "VMovB32":
                return EmitVectorAssignment(instruction, body, raw0 => raw0, out error);

            case "VFmacF32":
                return EmitVectorFloatAssignment(
                    instruction,
                    body,
                    (f, destination) => $"fma({f[0]}, {f[1]}, as_type<float>(v{destination}))",
                    sourceCount: 2,
                    out error);

            case "VFmaF32":
            case "VMadF32":
            case "VFmamkF32":
            case "VFmaakF32":
                // The decoder orders sources so the semantic is always fma(s0, s1, s2)
                // (for fmamk/fmaak the literal is placed in the matching slot).
                return EmitVectorFloatAssignment(
                    instruction,
                    body,
                    (f, _) => $"fma({f[0]}, {f[1]}, {f[2]})",
                    sourceCount: 3,
                    out error);

            case "VMulLoU32":
            case "VMulLoI32":
                return EmitVectorAssignment2(instruction, body, (a, b) => $"{a} * {b}", out error);

            case "VMulHiU32":
                return EmitVectorAssignment2(instruction, body, (a, b) => $"mulhi({a}, {b})", out error);

            case "VMulHiI32":
                return EmitVectorAssignment2(
                    instruction,
                    body,
                    (a, b) => $"as_type<uint>(mulhi(as_type<int>({a}), as_type<int>({b})))",
                    out error);

            default:
                if (instruction.Encoding == Gen5ShaderEncoding.Mubuf &&
                    instruction.Opcode.StartsWith("BufferStoreDword", StringComparison.Ordinal))
                {
                    return EmitBufferStore(instruction, bindingIndexByPc, body, out error);
                }

                error = "unsupported opcode in the MSL spike subset";
                return false;
        }
    }

    private static bool EmitBufferStore(
        Gen5ShaderInstruction instruction,
        IReadOnlyDictionary<uint, int> bindingIndexByPc,
        StringBuilder body,
        out string error)
    {
        error = string.Empty;
        if (instruction.Control is not Gen5BufferMemoryControl control)
        {
            error = "buffer store without buffer control";
            return false;
        }

        if (control.IndexEnabled || control.OffsetEnabled)
        {
            error = "indexed/offset buffer addressing is outside the spike subset";
            return false;
        }

        if (!bindingIndexByPc.TryGetValue(instruction.Pc, out var bindingIndex))
        {
            error = "no global-memory binding covers this store";
            return false;
        }

        // Same address model as the SPIR-V translator with index/offset disabled:
        // the immediate byte offset alone selects the dword.
        var baseDword = (uint)control.OffsetBytes >> 2;
        body.AppendLine("    if ((s126 & gen5_lane_mask) != 0u)");
        body.AppendLine("    {");
        for (uint dword = 0; dword < control.DwordCount; dword++)
        {
            body.AppendLine(
                $"        guest_buffer{bindingIndex}[{baseDword + dword}u] = v{control.VectorData + dword};");
        }

        body.AppendLine("    }");
        return true;
    }

    private static bool EmitVectorAssignment(
        Gen5ShaderInstruction instruction,
        StringBuilder body,
        Func<string, string> expression,
        out string error)
    {
        if (!TryGetRawSource(instruction, 0, out var raw0, out error) ||
            !TryGetVectorDestination(instruction, out var destination, out error) ||
            !RejectVop3Modifiers(instruction, out error))
        {
            return false;
        }

        AppendGuardedVectorWrite(body, destination, expression(raw0));
        return true;
    }

    private static bool EmitVectorAssignment2(
        Gen5ShaderInstruction instruction,
        StringBuilder body,
        Func<string, string, string> expression,
        out string error)
    {
        if (!TryGetRawSource(instruction, 0, out var raw0, out error) ||
            !TryGetRawSource(instruction, 1, out var raw1, out error) ||
            !TryGetVectorDestination(instruction, out var destination, out error) ||
            !RejectVop3Modifiers(instruction, out error))
        {
            return false;
        }

        AppendGuardedVectorWrite(body, destination, expression(raw0, raw1));
        return true;
    }

    private static bool EmitVectorFloatAssignment(
        Gen5ShaderInstruction instruction,
        StringBuilder body,
        Func<string[], uint, string> expression,
        int sourceCount,
        out string error)
    {
        var floats = new string[sourceCount];
        for (var index = 0; index < sourceCount; index++)
        {
            if (!TryGetRawSource(instruction, index, out var raw, out error))
            {
                return false;
            }

            floats[index] = $"as_type<float>({raw})";
        }

        if (!TryGetVectorDestination(instruction, out var destination, out error) ||
            !RejectVop3Modifiers(instruction, out error))
        {
            return false;
        }

        AppendGuardedVectorWrite(body, destination, $"as_type<uint>({expression(floats, destination)})");
        return true;
    }

    private static void AppendGuardedVectorWrite(StringBuilder body, uint destination, string expression)
    {
        // VALU writes only land on lanes whose EXEC bit is set.
        body.AppendLine("    if ((s126 & gen5_lane_mask) != 0u)");
        body.AppendLine("    {");
        body.AppendLine($"        v{destination} = {expression};");
        body.AppendLine("    }");
    }

    private static bool RejectVop3Modifiers(Gen5ShaderInstruction instruction, out string error)
    {
        error = string.Empty;
        if (instruction.Control is Gen5Vop3Control control &&
            (control.AbsoluteMask != 0 ||
             control.NegateMask != 0 ||
             control.OutputModifier != 0 ||
             control.Clamp ||
             control.ScalarDestination is not null))
        {
            error = "VOP3 abs/neg/omod/clamp modifiers are outside the spike subset";
            return false;
        }

        return true;
    }

    private static bool TryGetRawSource(
        Gen5ShaderInstruction instruction,
        int index,
        out string expression,
        out string error)
    {
        expression = string.Empty;
        error = string.Empty;
        if (index >= instruction.Sources.Count)
        {
            error = $"missing source operand {index}";
            return false;
        }

        var operand = instruction.Sources[index];
        switch (operand.Kind)
        {
            case Gen5OperandKind.VectorRegister:
                expression = $"v{operand.Value}";
                return true;
            case Gen5OperandKind.ScalarRegister:
                expression = $"s{operand.Value}";
                return true;
            case Gen5OperandKind.LiteralConstant:
                expression = $"0x{operand.Value:X8}u";
                return true;
            case Gen5OperandKind.EncodedConstant when TryDecodeInlineConstant(operand.Value, out var bits):
                expression = $"0x{bits:X8}u";
                return true;
            default:
                error = $"unsupported source operand encoding {operand.Value}";
                return false;
        }
    }

    private static bool TryGetVectorDestination(
        Gen5ShaderInstruction instruction,
        out uint destination,
        out string error)
    {
        destination = 0;
        error = string.Empty;
        if (instruction.Destinations.Count == 0 ||
            instruction.Destinations[0].Kind != Gen5OperandKind.VectorRegister)
        {
            error = "expected a vector destination";
            return false;
        }

        destination = instruction.Destinations[0].Value;
        return true;
    }

    private static bool TryGetScalarDestination(
        Gen5ShaderInstruction instruction,
        out uint destination,
        out string error)
    {
        destination = 0;
        error = string.Empty;
        if (instruction.Destinations.Count == 0 ||
            instruction.Destinations[0].Kind != Gen5OperandKind.ScalarRegister)
        {
            error = "expected a scalar destination";
            return false;
        }

        destination = instruction.Destinations[0].Value;
        return true;
    }

    private static bool TryCollectRegisters(
        Gen5ShaderState state,
        out SortedSet<uint> scalarRegisters,
        out SortedSet<uint> vectorRegisters,
        out string error)
    {
        error = string.Empty;
        scalarRegisters = new SortedSet<uint> { ExecLoRegister };
        vectorRegisters = new SortedSet<uint>();
        foreach (var instruction in state.Program.Instructions)
        {
            foreach (var operand in instruction.Sources)
            {
                CollectOperand(operand, scalarRegisters, vectorRegisters);
            }

            foreach (var operand in instruction.Destinations)
            {
                CollectOperand(operand, scalarRegisters, vectorRegisters);
            }

            if (instruction.Control is Gen5BufferMemoryControl buffer)
            {
                for (uint dword = 0; dword < buffer.DwordCount; dword++)
                {
                    vectorRegisters.Add(buffer.VectorData + dword);
                }
            }
        }

        return true;
    }

    private static void CollectOperand(
        Gen5Operand operand,
        SortedSet<uint> scalarRegisters,
        SortedSet<uint> vectorRegisters)
    {
        switch (operand.Kind)
        {
            case Gen5OperandKind.ScalarRegister:
                scalarRegisters.Add(operand.Value);
                break;
            case Gen5OperandKind.VectorRegister:
                vectorRegisters.Add(operand.Value);
                break;
        }
    }

    private static string Describe(Gen5ShaderInstruction instruction)
    {
        var destinations = string.Join(", ", instruction.Destinations);
        var sources = string.Join(", ", instruction.Sources);
        return destinations.Length != 0
            ? $"{instruction.Opcode} {destinations} <- {sources}"
            : sources.Length != 0
                ? $"{instruction.Opcode} {sources}"
                : instruction.Opcode;
    }

    // Mirrors Gen5SpirvTranslator.TryDecodeInlineConstant so both codegens agree on
    // the inline-constant table; lifted to the shared layer with the IR in the real
    // refactor.
    private static bool TryDecodeInlineConstant(uint encoded, out uint value)
    {
        if (encoded == 125)
        {
            value = 0;
            return true;
        }

        if (encoded is >= 128 and <= 192)
        {
            value = encoded - 128;
            return true;
        }

        if (encoded is >= 193 and <= 208)
        {
            value = unchecked((uint)-(int)(encoded - 192));
            return true;
        }

        var floatingPoint = encoded switch
        {
            240 => 0.5f,
            241 => -0.5f,
            242 => 1.0f,
            243 => -1.0f,
            244 => 2.0f,
            245 => -2.0f,
            246 => 4.0f,
            247 => -4.0f,
            248 => 1.0f / (2.0f * MathF.PI),
            _ => float.NaN,
        };
        if (float.IsNaN(floatingPoint))
        {
            value = 0;
            return false;
        }

        value = BitConverter.SingleToUInt32Bits(floatingPoint);
        return true;
    }
}
